### ISSUE TITLE
Cross-compile naive for Android

### ISSUE THREAD

**Issue by nekohasekai** [klzgrad/naiveproxy#185]
Hello, I want to make an android client that supports naiveproxy. Would you like to provide suggestions on how to cross compile naive for Android?

First of all, sorry for not being familiar with c/c++. It seems that the android toolchain inside the project has been removed. I tried to modify the configuration to compile with the Android NDK, but failed.

I have checked the issue of "Android Support". If you still insist on not supporting android, you can close this issue directly. Thank you for your reply.

**Comment by klzgrad** [comment]
I have no idea how to. It's not cross compile for Android because a binary does not run directly on Android. There is some apk packaging process which I don't have the energy to look into.

**Comment by klzgrad** [comment]
How do you plan to use it on Android? I didn't find an app that convert a socks5 proxy to VpnService.

**Comment by nekohasekai** [comment]
> How do you plan to use it on Android? I didn't find an app that convert a socks5 proxy to VpnService.

My [app](https://github.com/SagerNet/SagerNet) can convert a local socks5 server like trojan-go into a VPN service. (And use v2ray-core to implement routing)

**Comment by klzgrad** [comment]
What kind of ABI is it that your app uses? I see it builds libtrojan-go.so, but I can't find where it calls into any dynamic symbols or  how it passes parameters into it.

There is https://github.com/SagerNet/SagerNet/blob/8fbc6ef71705b4580a9da6822fe7a8a96eef0751/app/src/main/java/io/nekohasekai/sagernet/bg/ProxyInstance.kt#L265, but does it start a new process or what?

**Comment by nekohasekai** [comment]
> What kind of ABI is it that your app uses?
Depending on which one is installed by the user, I compile four abi so and then release four apk (because 3/4 of the universal apk is wasted)

> passes parameters into it.
Through the configuration file (https://github.com/SagerNet/SagerNet/blob/8fbc6ef71705b4580a9da6822fe7a8a96eef0751/app/src/main/java/io/nekohasekai/sagernet/fmt/trojan_go/TrojanGoFmt.kt#L112)

> but does it start a new process or what?
Yes, a new process. shadowsocks(r) uses this method.

**Comment by klzgrad** [comment]
libtrojan-go.so is a regular executable, not shared library?

**Comment by nekohasekai** [comment]
> libtrojan-go.so is a regular executable, not shared library?

Yes

**Comment by klzgrad** [comment]
I think you are misusing the .so suffix.

**Comment by nekohasekai** [comment]
> I think you are misusing the .so suffix.

Maybe there are any restrictions, I don't know. shadowsocks uses libsslocal.so so I did the same.

**Comment by nekohasekai** [comment]
![图片](https://user-images.githubusercontent.com/56506714/118346154-0763ab80-b56c-11eb-8a00-5e602c86027f.png)

As you can see, all native libraries in the apk must use this 'libxx.so' format, otherwise it will be ignored by the android gradle plugin (I did not test whether the mandatory packaged apk can run correctly)

**Comment by klzgrad** [comment]
ok, i'll see what i can do

**Comment by klzgrad** [comment]
I want to add that what I meant by ABI is not the architecture, but how this binary will interface with the app and the rest of the system. I was expecting some kind of JNI interface, or some kind of shared library interface with JNI wrapper provided by yourself, or some kind of my_main(int my_argc, char** argv) which starts in a thread. But a separate process would work nonetheless.

**Comment by nekohasekai** [comment]
Using jni, I need to manually handle multiple instances in C and handle the state of the proxy in different processes. And, proxychains cannot be used.

**Comment by nekohasekai** [comment]
It should be available in [the new version](https://github.com/SagerNet/SagerNet/releases/tag/0.1-rc11) of SN, thank you for your support.

**Comment by klzgrad** [comment]
I think you should wait until I finish it.

**Comment by nekohasekai** [comment]
Ok

**Comment by klzgrad** [comment]
Although I still have a few issues to clean up, you can go ahead with the current build. I have tested the x86 build in Termux and arm and arm64 are tested in qemu automatically. Qemu has some issues and does not work with x86 amd x64 builds. That is what was taking time.

I review your usage for a bit. There are a few things:

I will rebase the entire history and force push to the master branch regularly (once every new Chrome stable release, plus occasional refactor like this time). If you have a git submodule pointing to a specific commit, it may break. May need to discuss a better way to synchronize version tracking here.

Try to not use the log option when naive is not directly started by the user, except for debugging, because this option prints personal data.

This build also downloads and uses Android NDK. If you copy it to src/third_party/android_ndk, or create a symlink there, naive build won't need to download Android NDK twice. See the Android part in get-clang.sh to see how it works.

**Comment by nekohasekai** [comment]
> Try to not use the log option when naive is not directly started by the user, except for debugging, because this option prints personal data.

The contents of android logcat are theoretically safe (without being rooted, only adb and the app itself can read it), and the log buffer is usually only 128k, which we sometimes need to determine connection problems; a logging switch is in my plan (off by default).

> f you copy it to src/third_party/android_ndk

I tried "ln -s" directly, but it seems that something like .gn is missing and something went wrong, but git clone works.

**Comment by nekohasekai** [comment]
> will rebase the entire history and force push to the master branch regularly

Maybe following the tag is a solution. It seems that as long as the tag exists, github will keep the commit even if it is not in any branch.

**Comment by klzgrad** [comment]
What something went wrong? I'm hoping to optimize this build to not download too much. Android NDK is quite big to clone. I would imagine like this:

cd naive/src/third_party
ln -s $ANDROID_HOME/ndk/x.y.z android_ndk

Tracking tags sounds good. Use the latest official release tags, which are meant for general users. This all is not regular git workflow, because this repo works as a patch series on top of Chrome upstream, which moves on its own. It gets messy really quick if it tracks Chrome's version and changes in the patches in one place. So github releases seems to be the best place to track changes in this repo. I also write some short release notes there.

**Comment by nekohasekai** [comment]
> What something went wrong?

![Image](https://user-images.githubusercontent.com/56506714/118590146-75121080-b7d4-11eb-9769-bded18e9ac56.png)

```
ERROR at //third_party/zlib/BUILD.gn:339:17: Unable to load "/home/sekai/Projects/SagerNet/naive-plugin/src/main/jni/naiveproxy/src/third_party/android_ndk/BUILD.gn".
      deps += [ "//third_party/android_ndk:cpu_features" ]
```

**Comment by klzgrad** [comment]
https://chromium.googlesource.com/android_ndk/+/refs/heads/main/BUILD.gn

If there is no particular reason for this NDK to not have it you can put it there, it's small.

**Comment by nekohasekai** [comment]
It seems that there is no problem, let me wait for the compilation result.

**Comment by nekohasekai** [comment]
It has no problem.
