### ISSUE TITLE
[Feature request] Standalone QUIC-to-SOCKS proxy

### ISSUE THREAD

**Issue by hvonw** [klzgrad/naiveproxy#23]
Hi @klzgrad.
First of all really thank you for your efforts.
Naïve is 2X faster compared to other complex authenticated, traffic encrypted alternatives.
If it's not much work to do can you please add support for standalone usage? 
(client/server QUIC -UDP only transport)

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/blob/master/USAGE.txt#L43

Naive can already be used as a client-side SOCKS to QUIC proxy as above. Chromium doesn't have much code to create a proper QUIC server. Recommend using Caddy as a QUIC proxy server.

Last time I tested it, https://github.com/klzgrad/naiveproxy/releases/tag/v76.0.3809.12, Chromium's QUIC version isn't always compatible with Caddy's QUIC version. And most importantly, QUIC is slower than regular https (conservative congestion control, ISPs in China drop UDP etc). So QUIC support is only experimental before it becomes actually faster. If you can't find information for testing this setup I can give some instructions.

**Comment by btwiuse** [comment]
Hi, @klzgrad 

I'm the maintainer of the [caddy-with-quic](https://aur.archlinux.org/packages/caddy-with-quic/) package on AUR (FYI It's a fork from [caddy-with-cgi](https://aur.archlinux.org/packages/caddy-with-cgi/) with patch from this wiki page [Caddy-with-QUIC](https://github.com/klzgrad/naiveproxy/wiki/Caddy-with-QUIC)). 

I don't know if it works for you, but for me it doesn't work at all. On the client side, all I get are errors like these:
```
[0930/181250.905503:INFO:naive_proxy.cc(163)] Connection 64 closed: ERR_QUIC_PROTOCOL_ERROR                                                        
[0930/181250.905539:INFO:naive_proxy.cc(163)] Connection 63 closed: ERR_QUIC_PROTOCOL_ERROR 
[0930/181250.905575:INFO:naive_proxy.cc(163)] Connection 62 closed: ERR_QUIC_PROTOCOL_ERROR                                                        
```
Might be off topic, but is this what you mean by saying `Chromium's QUIC version isn't always compatible with Caddy's QUIC version. `, or because I missed something important in the build process, or maybe I have an incorrect setup? I think I need some pointers

**Comment by btwiuse** [comment]
https://www.chromium.org/quic/playing-with-quic
https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/tools/quic_toy_server.cc

Chromium src does include a simple impl of quic server, is this what we need?

**Comment by klzgrad** [comment]
It's in the release notes

> Chromium v76 has upgraded from gQUIC to IETF QUIC, which doesn't work with Caddy yet.

Caddy just had this https://github.com/caddyserver/caddy/pull/2727. I suppose we can reopen the test case.

**Comment by klzgrad** [comment]
A while ago I looked into if I could make a quic server out of Chromium because Caddy's quic was totally not working. The answer was no, because https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/tools/quic_server.h?q=quic_server.h&sq=package:chromium&dr=CSs&l=8 the code itself isn't meant as a high-performance server and it's really awkward to function as a forward proxy, as you can understand, because Chromium is not designed as a server. Once Caddy's quic was working again the need for a Chromium QUIC server is no more. Even regardless of performance, using Caddy QUIC as a frontend is still better than a handmade QUIC server because Caddy is used by many.

Google is trying to open source QUICHE https://quiche.googlesource.com/quiche (while Cloudflare open sourced the same fucking name https://github.com/cloudflare/quiche), which "powers Chromium as well as Google's QUIC servers". That's a good sign, but still I have to wait and see what becomes of it.

**Comment by btwiuse** [comment]
Well explained. Thanks for the clarification

**Comment by klzgrad** [comment]
Looks like Caddy's IETF QUIC in https://github.com/caddyserver/caddy/pull/2727 is only for Caddy v2 not v1. And Caddy v2 is still long way from production ready.

I added `--quic-version` in https://github.com/klzgrad/naiveproxy/releases/tag/v77.0.3865.90-3. Now you should be able to avoid ERR_QUIC_PROTOCOL_ERROR with `./naive --quic-version=43 ...`. I just tested it fine.

**Comment by op69qs** [comment]
Can you provide  Caddy v2 example configuration ? Thanks

**Comment by klzgrad** [comment]
I can't, since I haven't used Caddy v2.
