### ISSUE TITLE
How to use haproxy to do the load balance in client side if I have multiple naiveproxy servers

### ISSUE THREAD

**Issue by cary-sas** [klzgrad/naiveproxy#343]
Hello, 
Sorry for opening such issue, my knowledge of haproxy is limited. 
Suppose I have multiple naiveproxy servers in different regions,  how can I use haproxy (client side) to do the load balance ? 
Do you have any reference example or configure template of haproxy?  
I searched and find a similar topic in close issue #179 .But I still need to confirm with you, since the topic has passed more than one year.

**Comment by klzgrad** [comment]
Try --insecure-concurrency.

**Comment by klzgrad** [comment]
I'm asking to use insecure concurrency for load balancing instead of haproxy. It's irrelevant to naiveproxy whether haproxy can be used to load balance it.

**Comment by klzgrad** [comment]
I don't think it's possible to do it with haproxy because haproxy does not understand the proxy protocols, socks5 or http to have the information on the quality of proxied connections to make load balancing decisions.

This is possible to do inside naiveproxy, but the demand is not strong enough yet to justify coding time.
