### ISSUE TITLE
Discuss: Certificate signed with self-signed CA.

### ISSUE THREAD

**Issue by tomac4t** [klzgrad/naiveproxy#38]
> See "Generate certificates" in https://www.chromium.org/quic/playing-with-quic and https://source.chromium.org/chromium/chromium/src/+/master:docs/linux/cert_management.md (though you don't actually need certutil for adding root CA; you can do that in the browser with GUI). https://github.com/klzgrad/naiveproxy/issues/37#issuecomment-582759151

I see it make possible to use a certificate signed with self-signed CA. To those who don't have a domain name, this will save them a lot of money. It can write an IP address in SSL certificate's "Common Name(CN)". Then run `./naive --listen=socks://127.0.0.1:1080 --proxy=https://aa.bb.cc.dd/`.

The remain question is naive doesn't allow proxy URL contain an IP address:

https://github.com/klzgrad/naiveproxy/blob/f7ce953587a058ed7828fec988dcd779619a58f5/src/net/tools/naive/naive_proxy_bin.cc#L71

https://github.com/klzgrad/naiveproxy/blob/f7ce953587a058ed7828fec988dcd779619a58f5/src/net/tools/naive/naive_proxy_bin.cc#L331-L341

I don't see it is necessary to replace `server_name` to "example", because It shouldn't be sent `server_name` when you visit an IP address directly, like https://1.1.1.1/.

Another problem is missing `server_name` will change the ClientHello fingerprint, and make it become uncommon traffic(Hoping the Chromium will enable the DoH by default:-)): 
https://tlsfingerprint.io/id/e94fcb2176c0b827
https://tlsfingerprint.io/compare/bbf04e5f1881f506/e94fcb2176c0b827

Edited: The way to workaround now is write both IP address and domain name(eg. `example`) in "subjectAltName(SAN)".

What do you think? @klzgrad

**Comment by klzgrad** [comment]
Have you tried anything you said here? If it does work then maybe you have a point, otherwise...

`// SNI should only contain DNS hostnames not IP addresses per RFC 6066. `

This comment was a summary of why it didn't work with naked ip addresses. Either this SNI rule stops proxies with naked ip addresses from working, or it was other CA base requirements that made it problematic to use naked ip addresses in certificates. I forgot which one it was and for reasons below I'm not bothered to test it.

In general using naked ip addresses and even self-signed CAs is a red flag in the PKI system because it stands out from most other certificates. I read papers and I knew the GFW is surveying circulating certificates. There is or are several 'trustworthiness' rankings of certificates, and the rankings are used to classify malwares, and of course, hidden tunnels of adversaries. The way to rank certificates is not too far from standard traffic classification, that is, feature extraction and learning. The features of a certificate is then obviously the way and parameters used to generate it. Then my opinion is that what you described (which is what I tried first; don't know if it has become working again since then) is one of the rarest way to generate certificates, as most certificates are either signed by a known CA or self-signed, and as a consequence it stands out among all certificates.

**Comment by klzgrad** [comment]
I think I wrote more here https://github.com/trojan-gfw/trojan/issues/14 about the best practices wrt certificates. In short the best practice now is to use Let's Encrypt.

**Comment by tomac4t** [comment]
（还是使用母语，逻辑清楚一些。）

我也认为使用受信任的证书是最佳实践，目前也是这么做的。看到你之前的评论，我也在思考是否有使用自签名证书的可行性，是否存在更多的“玩法”。我确实尝试了上述想法，注释掉那部分代码，使用没有发现遇到问题。ClientHello 和预期那样缺少了 `server_name` 扩展（https://tlsfingerprint.io/id/e94fcb2176c0b827 ），行为与直接使用 Chromium 访问裸 IP 一致（eg. https://1.1.1.1/ ）。

这是 Chromium 当前版本最常见指纹和缺少 `server_name` 扩展指纹的对比，只有 `server_name` 有和无的区别（前者排名是1，后者是1300多，勉强可以接受）：
https://tlsfingerprint.io/compare/bbf04e5f1881f506/e94fcb2176c0b827

不过为 IP 申请证书的要求多、代价高（对 IP 拥有所有权、组织验证证书），应该不会有人遇到这个问题。

> I read papers and I knew the GFW is surveying circulating certificates. 

刚去搜了一下，想起来很多年前确实有看过 GFW 屏蔽 StartCom 以及自签名证书的[新闻](https://www.solidot.org/story?sid=35250)，这个我确实以为 GFW 不会做到这么精细。论文暂时没有找到。（由于这一点，考虑关闭本 Issue。）

* * *
PS. 看了 Houmansadr2013 论文，NaiveProxy 确实是做到了最佳实践。前段时间正好看到了 [TLS指纹调查.md](https://gist.github.com/klzgrad/25b2612d266a450abca6129a7ca595a4)，它信息量比我想象中大，如果没想错，那位伊朗人无法使用 V2ray 的原因正是因为两种指纹的差异。dcf 说他们 Meek 解决 ClientHello 指纹问题一个实现是使用 headless Firefox，另一个是使用 [uTLS](https://gitlab.com/yawning/utls)，来确保和火狐 ClientHello 指纹的一致。@klzgrad

**Comment by klzgrad** [comment]
论文要在知网上找。除了找标题还要看通讯作者历史记录，和项目资金编号。

**Comment by klzgrad** [comment]
I removed the part you requested. It was meant to make testing easier, and testing is now possible without it.
