### ISSUE TITLE
UDP over TCP

### ISSUE THREAD

**Issue by NadiaGarcia6** [klzgrad/naiveproxy#425]
Hi,

WhatsApp, Google Meet calls use UDP protocol.
When we use NaivyProxy on mobile phones, it is not possible to make and receive VoIP calls.
Do you have any plans to add UDP protocol?

Regards,

**Comment by klzgrad** [comment]
I don't.

**Comment by reeceyng** [comment]
I am using [sing-box](https://github.com/SagerNet/sing-box/)(windows) and [sagernet](https://github.com/SagerNet/sagernet)(android) to transfer udp over tcp
Server side need patched [caddy](https://github.com/SagerNet/forwardproxy)

**Comment by oit63** [comment]
thanks,sing-box(linux) + haproxy + naiveproxy works perfect, both tcp and udp.

**Comment by silenaker** [comment]
> I am using [sing-box](https://github.com/SagerNet/sing-box/)(windows) and [sagernet](https://github.com/SagerNet/sagernet)(android) to transfer udp over tcp Server side need patched [caddy](https://github.com/SagerNet/forwardproxy)

thanks for your invaluable advice, this is very useful, but it has a problem with README

I'm not a go expert and I don't know caddy, the command
`xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/sagernet/forwardproxy@latest`
has a problem, which caused the terminal output to be stuck forever in the downloading of a certain library without any prompt, I had no idea what was going on and there were no other useful information, it was too painful, It's a waste of my afternoon trying to sort it out. the correct command is this
`xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/sagernet/forwardproxy@caddy2 `
that replace the **latest** with **caddy2**

whether it's a typo or something else, this little slip-up is too bad for people who don't know

**Comment by silenaker** [comment]
> > I am using [sing-box](https://github.com/SagerNet/sing-box/)(windows) and [sagernet](https://github.com/SagerNet/sagernet)(android) to transfer udp over tcp
> > Server side need patched [caddy](https://github.com/SagerNet/forwardproxy)
> 
> hi, how does sing-box use naiveproxy under windows? It seems that the naiveproxy implementation of sing-box can only be used on the server side?

I have tested the forked package [github.com/SagerNet/forwardproxy](https://github.com/SagerNet/forwardproxy), now it cannot be built successfully and will be stucked on getting some packages, i use the original one [github.com/klzgrad/forwardproxy](https://github.com/klzgrad/forwardproxy) and copy modifications to it and build successfully, and there is another important problem on the patched code, the patched code use [uot](https://github.com/SagerNet/sing/blob/dev/common/uot/server.go) package to implement udp relay, it has a mistake that actually the udp over tcp will not work, i have forked and [pulled request](https://github.com/SagerNet/sing/pull/42) to it, using my [fork](https://github.com/silenaker/sing), uot will work correctly, it may be difficult for non-Go and non-network experts because I'm also new to it and it took me a while to figure it out, if you need some installation and configuration tutorials, you can go to their website and README, after all, it's not much of a concern

**Comment by klzgrad** [comment]
You or anyone interested in this can explain this use case because I cannot understand the value proposition of udp over tcp. This tool is for circumvention only and is not a general proxy. If you need udp for something that is not blocked by a mitm but by the endpoint due to region locks or other technical or copyright issues, then this tool is not designed for it. You can use a dedicated udp proxy along with this. Do not need to put every feature in one tool.

**Comment by silenaker** [comment]
> You or anyone interested in this can explain this use case because I cannot understand the value proposition of udp over tcp. This tool is for circumvention only and is not a general proxy. If you need udp for something that is not blocked by a mitm but by the endpoint due to region locks or other technical or copyright issues, then this tool is not designed for it. You can use a dedicated udp proxy along with this. Do not need to put every feature in one tool.

i totally agree with your design proposition, but for users, they just want to use it simple and don't even want to spend too much time on figuring out their configuration, while for some other few people, they are happy to toss it around and even find it more interesting, i don't really have much need for udp scenarios, I just want a stable solution for video or voice calling scenarios that may come up in the future, and even i am afraid of the deny access of public dns services such as google dns, I don't care about the latency introduced by udp over tcp, I just want to make sure that a more complete solution can avoid my future troubles, for most users, it's ok to barely enough to work, and not work, it's a big problem

**Comment by oit63** [comment]
> > > I am using [sing-box](https://github.com/SagerNet/sing-box/)(windows) and [sagernet](https://github.com/SagerNet/sagernet)(android) to transfer udp over tcp
> > > Server side need patched [caddy](https://github.com/SagerNet/forwardproxy)
> > 
> > 
> > hi, how does sing-box use naiveproxy under windows? It seems that the naiveproxy implementation of sing-box can only be used on the server side?
> 
> I have tested the forked package [github.com/SagerNet/forwardproxy](https://github.com/SagerNet/forwardproxy), now it cannot be built successfully and will be stucked on getting some packages, i use the original one [github.com/klzgrad/forwardproxy](https://github.com/klzgrad/forwardproxy) and copy modifications to it and build successfully, and there is another important problem on the patched code, the patched code use [uot](https://github.com/SagerNet/sing/blob/dev/common/uot/server.go) package to implement udp relay, it has a mistake that actually the udp over tcp will not work, i have forked and [pulled request](https://github.com/SagerNet/sing/pull/42) to it, using my [fork](https://github.com/silenaker/sing), uot will work correctly, it may be difficult for non-Go and non-network experts because I'm also new to it and it took me a while to figure it out, if you need some installation and configuration tutorials, you can go to their website and README, after all, it's not much of a concern
> 
> singbox -> naive -> caddy/forwardproxy(patched by uot) worked perfectly, i have tested on windows and linux, even use clash as the front end of a transparent proxy (clash -> singbox -> naive -> caddy/forwardproxy)，it all works very well, singbox seems to be the next generation of proxy tools, but it doesn't support configuring remote rules and outbounds, so it's not as easly maintainable as clash, and clash doesn't support udp over tcp, they are all not perfect
> 
> hopefully, this solution will replace trojan, because the server ip i used with trojan was blocked just last week

我用的就是singbox，支持uot的
