### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by kouhi** [klzgrad/naiveproxy#45]
Thanks for building this tool. We've been testing in Iran. Works pretty well. 

Any thoughts on developing an Android app?

**Comment by klzgrad** [comment]
I have rough ideas of how, but haven't got time yet to do it.

The basic idea is use Android's VpnService, which exposes a Linux tun device where a read() call returns an IP packet. TCP connections over these packets can be reassembled and demultiplexed into separate connections through lwIP, and then programmatically fed into naiveproxy proper. Aside from this there also needs to be a frontend for user config etc. The main tricky part now is how to tune lwIP so that it works efficiently. lwIP has its own memory pooling which is problematic if used within naiveproxy; I haven't found the best way to do it yet. After these it would be a pure time consuming process of creating an Android app.

In the mean time you can check Trojan's Android app called Igniter.

**Comment by fedoranhowl** [comment]
感谢作者，我很喜欢你的作品，它在我所有的vps上都表现良好，效果甚至超过成熟的v2ray与trojan,不过因为移动端的原因现在一直在用trojan.
  辛苦了！

**Comment by random755** [comment]
Any details on what's wrong with lwip's memory pooling?

**Comment by rvpn** [comment]
just managed to install NP today.. so far looking good. pretty stable. i hope you will be working on android client next..

**Comment by rvpn** [comment]
trojan is slow and buggy according to this review https://www.youtube.com/watch?v=oG8y-6s6Aek

**Comment by NightMachinary** [comment]
[**@klzgrad**](https://github.com/klzgrad) commented on [Mar 4, 2020, 6:51 PM GMT+3:30](https://github.com/klzgrad/naiveproxy/issues/45#issuecomment-594595346 "2020-03-04T15:21:23Z - Replied by Github Reply Comments"):
> I have rough ideas of how, but haven't got time yet to do it.
> 
> The basic idea is use Android's VpnService, which exposes a Linux tun device where a read() call returns an IP packet. TCP connections over these packets can be reassembled and demultiplexed into separate connections through lwIP, and then programmatically fed into naiveproxy proper. Aside from this there also needs to be a frontend for user config etc. The main tricky part now is how to tune lwIP so that it works efficiently. lwIP has its own memory pooling which is problematic if used within naiveproxy; I haven't found the best way to do it yet. After these it would be a pure time consuming process of creating an Android app.
> 
> In the mean time you can check Trojan's Android app called Igniter.

Could you integrate trojan with caddy as well? It makes setting up everything so elegant and painless.

**Comment by klzgrad** [comment]
I decide not to support this.
