### ISSUE TITLE
Bug: WARNING:address_sorter_posix.cc(459)] FromSockAddr failed on netmask

### ISSUE THREAD

**Issue by bluemiaomiao** [klzgrad/naiveproxy#594]
```
➜  naiveproxy-v119.0.6045.66-1-mac-arm64 ./naive --config ./config.json                    
[1114/170014.241148:WARNING:address_sorter_posix.cc(459)] FromSockAddr failed on netmask

➜  naiveproxy-v119.0.6045.66-1-mac-arm64 sudo ./naive --config ./config.json
Password:
[1114/170028.030936:WARNING:address_sorter_posix.cc(459)] FromSockAddr failed on netmask
```

**Comment by Chilledheart** [comment]
Maybe you should check `listen` field inside `config.json` file to make sure if it is valid.

**Comment by bluemiaomiao** [comment]
```json
{
  "listen": "socks://127.0.0.1:5000",
  "proxy": "https://hello:world@example.com",
  "log": "/opt/naive/naive.log"
}
```

This is my client configuration. @Chilledheart

**Comment by Chilledheart** [comment]
Okay, it is harmless. I checked the code `AddressSorterPosix::OnIPAddressChanged` at https://chromium.googlesource.com/chromium/src/+/refs/heads/main/net/dns/address_sorter_posix.cc#456 and it only tried to list all network interfaces via `getifaddrs` call.

And it seems only affecting when it is startuping. Hopefully, it is fixed in later versions.

**Comment by klzgrad** [comment]
Chrome issue and low impact. No fix is planned in here.
