### ISSUE TITLE
Android client support?

### ISSUE THREAD

**Issue by segfault-bilibili** [klzgrad/naiveproxy#632]
https://github.com/SagerNet/sing-box/issues/1099 has already been closed as not planned.

**Comment by segfault-bilibili** [comment]
sing-box for Android has no naive outbound (client) support, at least for now.

SagerNet project has already been archived.

**Comment by zedifen** [comment]
Currently this repo provides NekoBox-compliant plugin as [stated in README](https://github.com/klzgrad/naiveproxy?tab=readme-ov-file#download-na%C3%AFveproxy). If you'd like to use naiveproxy on Android (with GUI support), you could download NekoBox and install the naiveproxy plugin as well.

NekoBox is a lot like SagerNet, but it appears to have adopted sing-box as its underlying library.

And while this naiveproxy plugin may also fit SagerNet/SagerNet, but since it's archived, it's not recommended to do so.

If you'd like to use sing-box with naiveproxy (on Android with GUI support), then you may not open a issue under naiveproxy, since it should be a sing-box issue. You could try starting a discussion, or at least made this issuse title more specific.

**Comment by segfault-bilibili** [comment]
Thanks but will naive plugin still be updated?

**Comment by zedifen** [comment]
@segfault-bilibili I'm not a maintainer of naiveproxy, and even if I am one, I can make no guarantee on support for a platform or for the entire project. However, considering that Android is one of major platforms, it should be easy to maintain naiveproxy for it.

To be more specific, currently the naiveproxy "plugin" is basically a wrapped binary for the Android platform. Building it should be easy as long as Chrome can build for Android, which means naiveproxy plugin for Android can be easily published together with ones for other platforms.

But since the plugin is just a wrapped binary, its usability also depends on whether you can get support from the app that calls it.

**Comment by Chilledheart** [comment]
@segfault-bilibili if you don't mind, you can try [yass' android client](https://github.com/Chilledheart/yass/releases/download/1.8.1/yass-android-release-arm64-1.8.1.apk) which is written by me. no plugins and no other clients are required.

**Comment by UncleUncleWang** [comment]
After NekoBox changed developers, the frequency of maintenance and updates has been very low. Can plug-ins be developed that are compatible with other clients? NekoBox is indeed the most user-friendly GUI client out there, there are almost no other options

**Comment by klzgrad** [comment]
> the frequency of maintenance and updates has been very low

Is this a problem? Why do you need frequent updates?

**Comment by segfault-bilibili** [comment]
Because this project seems to be rebased upon latest chromium network stack periodically. I don't know whether it's necessary to keep it up from the user's perspective either.

If it's actually not needed, glad to hear that~

**Comment by segfault-bilibili** [comment]
Actually I made a PowerShell script periodically executed by scheduled tasks to automatically keep naive.exe latest. This is for Windows. As for Android, in the past the Play market had automatically kept the naive plugin latest as well.

If it's better to keep naive plugin latest, I think maybe GitHub actions can do this.

**Comment by segfault-bilibili** [comment]
Or maybe it's already close to the point that this project has done its job? Maybe nobody should expect one strategy to work forever, after all. I heard that some people already reported that the censors have now gained ability to detect it.

It's now working fine for me however. But maybe I should find some other way in advance.

**Comment by klzgrad** [comment]
https://github.com/klzgrad/naiveproxy/releases/download/v124.0.6367.54-2/naiveproxy-plugin-v124.0.6367.54-2-arm64-v8a.apk

?

**Comment by segfault-bilibili** [comment]
Uh-oh. Got it.

**Comment by UncleUncleWang** [comment]
> > the frequency of maintenance and updates has been very low
> 
> Is this a problem? Why do you need frequent updates?

Recently, nekobox's Google play developer account went out of control and a non-open source version containing ads was uploaded. In fact, after changing developers, not only did the update frequency decrease, but the developers did not pay attention at all and even lost control of their accounts, which put its users at great risk. If there are no other simple and easy-to-use clients to support it, many junior users will not be able to use naive proxy. It is really a pity.

**Comment by UncleUncleWang** [comment]
https://github.com/MatsuriDayo/NekoBoxForAndroid?tab=readme-ov-file#%E4%B8%8B%E8%BD%BD--downloads
