### ISSUE TITLE
求助：caddy运行出错

### ISSUE THREAD

**Issue by fedoranhowl** [klzgrad/naiveproxy#64]
抱歉，此帖非issues，应该是caddy方面的配置问题（本人小白一个），参考了网上的文章
之前能配置成功，最近重新配置时出错：“caddy.service: Failed at step USER spawning /usr/bin/caddy: No such process”，还有一行错误提示忘记了。
因为caddy.service原来的脚本不在了，新的脚本在此地址：wget https://raw.githubusercontent.com/caddyserver/dist/master/init/caddy.service，这个文件我也看不出哪有问题，所以也不知道是不是这个脚本导致的错误。

**Comment by fedoranhowl** [comment]
https://arcdetri.github.io/naiveproxy-debian-10-windows.html
https://allinfa.com/naiveproxy-caddy.html
之前几乎照搬这两篇文章配置的

**Comment by AttorneyFan** [comment]
这个问题我也遇到过，产生这个问题的原因是：caddy 2即将发布，所以作者删除了github上的针对caddy1 的caddy.service文件，新发布的caddy.service是针对caddy 2的

**Comment by AttorneyFan** [comment]
对于这个问题，我的解决方式是：
一、遵照这篇文章https://allinfa.com/naiveproxy-caddy.html里的步骤，下载caddy.service（这个版本是针对caddy 2的）；
二、使用nano /etc/systemd/system/caddy.service命令，将caddy.service的内容替换为旧版本的，旧版本caddy.service内容来自于我的其他vps机器；
三、如果你手头没有旧版本caddy.service文件，可以复制以下内容，使用nano /etc/systemd/system/caddy.service命令打开并替换掉；
步骤说的有点啰嗦，简而言之，就是把文件内容替换掉

[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

; Do not allow the process to be restarted in a tight loop. If the
; process fails to start, something critical needs to be fixed.
StartLimitIntervalSec=14400
StartLimitBurst=10

[Service]
Restart=on-abnormal

; User and group the process will run as.
User=www-data
Group=www-data

; Letsencrypt-issued certificates will be written to this directory.
Environment=CADDYPATH=/etc/ssl/caddy

; Always set "-root" to something safe in case it gets forgotten in the Caddyfile.
ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
ExecReload=/bin/kill -USR1 $MAINPID

; Use graceful shutdown with a reasonable timeout
KillMode=mixed
KillSignal=SIGQUIT
TimeoutStopSec=5s

; Limit the number of file descriptors; see `man systemd.exec` for more limit settings.
LimitNOFILE=1048576
; Unmodified caddy is not expected to use more than that.
LimitNPROC=512

; Use private /tmp and /var/tmp, which are discarded after caddy stops.
PrivateTmp=true
; Use a minimal /dev (May bring additional security if switched to 'true', but it may not work on Raspberry Pi's or other devices, so it has been disabled in this dist.)
PrivateDevices=false
; Hide /home, /root, and /run/user. Nobody will steal your SSH-keys.
ProtectHome=true
; Make /usr, /boot, /etc and possibly some more folders read-only.
ProtectSystem=full
; … except /etc/ssl/caddy, because we want Letsencrypt-certificates there.
;   This merely retains r/w access rights, it does not add any new. Must still be writable on the host!
ReadWritePaths=/etc/ssl/caddy
ReadWriteDirectories=/etc/ssl/caddy

; The following additional security directives only work with systemd v229 or later.
; They further restrict privileges that can be gained by caddy. Uncomment if you like.
; Note that you may have to add capabilities required by any plugins in use.
;CapabilityBoundingSet=CAP_NET_BIND_SERVICE
;AmbientCapabilities=CAP_NET_BIND_SERVICE
;NoNewPrivileges=true

[Install]
WantedBy=multi-user.target

**Comment by fedoranhowl** [comment]
> 这个问题我也遇到过，产生这个问题的原因是：你使用的是caddy 1。而caddy 2即将发布，所以作者删除了github上的针对caddy1 的caddy.service文件，新发布的caddy.service是针对caddy 2的。

非常感谢你的回答，昨天也是搜索了半天知道了caddy2这么个东西，再看以后的配置文件使用json,还有格式各种看不懂，小白直接吓坏了。

**Comment by fedoranhowl** [comment]
> 对于这个问题，我的解决方式是：
> 一、遵照这篇文章[https://allinfa.com/naiveproxy-caddy.html里的步骤，下载caddy.service（这个版本是针对caddy](https://allinfa.com/naiveproxy-caddy.html%E9%87%8C%E7%9A%84%E6%AD%A5%E9%AA%A4%EF%BC%8C%E4%B8%8B%E8%BD%BDcaddy.service%EF%BC%88%E8%BF%99%E4%B8%AA%E7%89%88%E6%9C%AC%E6%98%AF%E9%92%88%E5%AF%B9caddy) 2的）；
> 二、使用nano /etc/systemd/system/caddy.service命令，将新版本caddy.service的内容替换为旧版本的，旧版本caddy.service文件来自于我的其他vps机器；
> 三、如果你手头没有旧版本caddy.service文件，可以复制以下内容，使用nano /etc/systemd/system/caddy.service命令打开并完全替换。
> 
> [Unit]
> Description=Caddy HTTP/2 web server
> Documentation=https://caddyserver.com/docs
> After=network-online.target
> Wants=network-online.target systemd-networkd-wait-online.service
> 
> ; Do not allow the process to be restarted in a tight loop. If the
> ; process fails to start, something critical needs to be fixed.
> StartLimitIntervalSec=14400
> StartLimitBurst=10
> 
> [Service]
> Restart=on-abnormal
> 
> ; User and group the process will run as.
> User=www-data
> Group=www-data
> 
> ; Letsencrypt-issued certificates will be written to this directory.
> Environment=CADDYPATH=/etc/ssl/caddy
> 
> ; Always set "-root" to something safe in case it gets forgotten in the Caddyfile.
> ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
> ExecReload=/bin/kill -USR1 $MAINPID
> 
> ; Use graceful shutdown with a reasonable timeout
> KillMode=mixed
> KillSignal=SIGQUIT
> TimeoutStopSec=5s
> 
> ; Limit the number of file descriptors; see `man systemd.exec` for more limit settings.
> LimitNOFILE=1048576
> ; Unmodified caddy is not expected to use more than that.
> LimitNPROC=512
> 
> ; Use private /tmp and /var/tmp, which are discarded after caddy stops.
> PrivateTmp=true
> ; Use a minimal /dev (May bring additional security if switched to 'true', but it may not work on Raspberry Pi's or other devices, so it has been disabled in this dist.)
> PrivateDevices=false
> ; Hide /home, /root, and /run/user. Nobody will steal your SSH-keys.
> ProtectHome=true
> ; Make /usr, /boot, /etc and possibly some more folders read-only.
> ProtectSystem=full
> ; … except /etc/ssl/caddy, because we want Letsencrypt-certificates there.
> ; This merely retains r/w access rights, it does not add any new. Must still be writable on the host!
> ReadWritePaths=/etc/ssl/caddy
> ReadWriteDirectories=/etc/ssl/caddy
> 
> ; The following additional security directives only work with systemd v229 or later.
> ; They further restrict privileges that can be gained by caddy. Uncomment if you like.
> ; Note that you may have to add capabilities required by any plugins in use.
> ;CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> ;AmbientCapabilities=CAP_NET_BIND_SERVICE
> ;NoNewPrivileges=true
> 
> [Install]
> WantedBy=multi-user.target

好的，多谢你！

**Comment by fedoranhowl** [comment]
重新尝试还是出错了,然后放弃caddy.service了....(我笨)
搜索了一个supervisor的教程:
apt -y install supervisor
systemctl enable supervisor
vim /etc/supervisor/conf.d/caddy.conf
#
[program:caddy]
priority=1
environment=CADDYPATH=/etc/ssl/caddy
directory=/etc/caddy
command=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile
autorestart=true
#
搞定,超级简单!

**Comment by tomac4t** [comment]
Caddy1 的 caddy.service example 在 v1 分支，并没有删除：https://github.com/caddyserver/caddy/blob/v1/dist/init/linux-systemd/caddy.service

“caddy.service: Failed at step USER spawning /usr/bin/caddy: No such process”，已经告诉你问题在哪里了，路径不对，`which caddy` 找一下 caddy 在哪里再到 caddy.service 替换掉就得了，并没有比你提到了 supervisor 复杂多少。也不必如此迂回地使用 supervisor 再去启子进程（当然不是不可以）。@fedoranhowl

**Comment by AttorneyFan** [comment]
> 回地使用 supervisor 再去启子进程（当然不是不可以）。

大神就是大神，透彻

**Comment by fedoranhowl** [comment]
多谢提醒，真心感谢！
