### ISSUE TITLE
[Non-issue] How come the first commit is only 4 days old?

### ISSUE THREAD

**Issue by aarav2you** [klzgrad/naiveproxy#650]
The first commit of this repository is 4 days old: https://github.com/klzgrad/naiveproxy/commit/0998318c6788160c4f320749ebe3a2df6a9f732c

Did the git history get deleted?

**Comment by zedifen** [comment]
When a Chromium version is released, it will be imported (as in the commit you've mentioned) and naiveproxy will then rebase its code onto it.

Also, GitHub sorts commits based on their commit dates instead of author dates. Usually commits get a new commit date when it's rebased / cherry-picked onto a new one, while its author date stays unchanged. To check a commit's author date, append `.patch` to the end of its URL on GitHub, or clone the repository to check locally.

If you'd like to view the history of naiveproxy, check the commits after the "import" one. Note that during the process of rebasing, certain commits may be dropped or merged together. You may want to check other release branches besides `master` to get to know more ancient histories.
