### ISSUE TITLE
Shadowrocket supports naiveproxy, should I choose https or http2？

### ISSUE THREAD

**Issue by U201413497** [klzgrad/naiveproxy#687]
I don't understand what the difference is between the two and which one would be better. Looking forward to your reply.

**Comment by klzgrad** [comment]
Shadowrocket has nothing to do with naiveproxy. Whatever it supports, it is not naiveproxy.

**Comment by Chilledheart** [comment]
[shadowrocket](https://apps.apple.com/us/app/shadowrocket/id932747118) is an alternative to [surge](https://apps.apple.com/us/developer/surge-networks-inc/id1442620677) in iOS world. I used shadowrocket previously as a cheap iOS client for naive while surge was too expensive (before I developed [yass for iOS](https://testflight.apple.com/join/6AkiEq09), a free iOS client for naive).

Both of shadowrocket and surge are __closed-source__ program. We don't know much about its internals. As far as I can tell, shadowrocket's padding support is broken time to time in real world and both of _https_ and _http2_ protocols are supported (there is one exception, that _https_ doesn't support padding by design).

**Comment by Chilledheart** [comment]
And I don't use iOS devices much these days, so that's all I can tell.

**Comment by U201413497** [comment]
> Both of shadowrocket and surge are **closed-source** program. We don't know much about its internals. As far as I can tell, shadowrocket's _padding_ support is broken time to time in real world and both of _https_ and _http2_ protocols are supported (there is one exception, that _https_ doesn't support _padding_ by design).
Thank you for your reply. I have used yass for iOS and it works. But the UI is rudimentary. I prefer VPN tools like shadowrocket, foxray, etc. I look forward to your improvements, and I also look forward to this tool being officially launched on the app store.

**Comment by Chilledheart** [comment]
> Thank you for your reply. I have used yass for iOS and it works. But the UI is rudimentary. I prefer VPN tools like shadowrocket, foxray, etc. I look forward to your improvements, and I also look forward to this tool being officially launched on the app store.

Thank you for your positive feedback. Yass is free and open source just like naiveproxy. Depending on the given situation, it may have some UI improvements under the pressure of the community.
