### ISSUE TITLE
CDN support?

### ISSUE THREAD

**Issue by darhwa** [klzgrad/naiveproxy#74]
Naiveproxy only directly serves on user's host server, but can't be fronted by CDN. CDNs don't support CONNECT method.

Would you like to extend usage scenerio of naiveproxy to cover CDN fronting? Currently I know this can be done by either websocket or using PUT/POST method to simulate a tunnel, like what v2ray does.

**Comment by klzgrad** [comment]
I'm against CDN fronting. Can't think of any actual benefit with it.

**Comment by AttorneyFan** [comment]
True server IP is hidden behind the CDN. Besides, the CDN can accelerate connection speed. These features may be very useful in China.

**Comment by klzgrad** [comment]
This is assuming you're freeloading the CDN for traffic proxying, which is likely formally an abuse in their terms of use. (Domain fronting was banned from major CDNs a while ago.) And there's no shortage of CDNs being blocked either.

The only case that is favorable for the CDN's case is when you have an extremely cheap server and free CDN proxying, the combination of the two somehow is faster than the naked server. But I consider this tool high-security and not for everyone, so unless I see very convincing proof this case is actually viable I'm not invested in this.

**Comment by tomac4t** [comment]
- I also aginst use CDN as a way of collateral freedom. Of course, CDNs would see it as abuse because the collateral damage also is unacceptable to them.

- Another reason which domain fronting was suspended in major CDNs is it can obfuscate with high reputation domains. [APT29](https://www.fireeye.com/blog/threat-research/2017/03/apt29_domain_frontin.html) and many other blue teams use this trick against the adversary. As far as I know, Cloudflare probably is _first_ CDN to [prohibit the domain fronting](https://bugs.torproject.org/14256). It's a bad option if you want to use CDN proxying with Cloudflare free plan.

- CDN support make it become a non-naive proxy ;)

- Another thread: https://github.com/klzgrad/naiveproxy/issues/10#issuecomment-478813442

**Comment by darhwa** [comment]
@klzgrad @tomac4t 

Thanks for clarifying. I'm new in this area and have seen the practice of CDN fronting is popular among v2ray users. Now I believe that your perspective about CDN is right.

**Comment by Alvin9999** [comment]
刚刚一个vps ip被封了，套CDN在某种程度上可以防止ip被墙。

**Comment by yearqp** [comment]
说实话，不论是套cdn还是不套cdn，只要被gfw探测到，就都会产生个人利益的损失和公共利益的损失。

**Comment by cercveil** [comment]
有个人给我回了句"现在是 2022 年 10 月，对于 Cloudflare 来说：域前置并不是免费套餐内的服务，而仅仅是利用 CDN 建立隧道我并不觉得是滥用，要知道免费服务 [Cloudflare Tunnel](https://blog.cloudflare.com/tunnel-for-everyone/) 相当于同类用途，有具体条款吗？"，被删了不知道怎么回事，那我就单独再回一句。
域前置既不在免费套餐里，也不在收费套餐里，在cf的社区https://community.cloudflare.com/t/is-it-possible-to-use-a-cloudflare-service-worker-as-a-proxy-web-server/145628/6和https://community.cloudflare.com/t/could-cloudflare-support-domain-fronting/200944已明确表明域前置不受cf的支持，不知你特意提个免费套餐是什么意思。
我看了一下cloudflare的服务条款，承认拿cloudflare来套vpn从而规避中国大陆的审查的的确确是一种滥用。但我上一条回复中关于vpn对主机商是滥用的观点仍然不变，在著名主机商搬瓦工的服务条款提及到
We do not tolerate the following activities on our servers:Open proxy servers (due to abuse committed through open proxies);vultr的使用政策也提到禁止Operation of Certain Network Services. Operating network services like open proxies, open mail relays, or open recursive domain name servers.尽管proxy实际上不等于vpn，但拿来翻墙的话，vpn确实充当"代理"用户访问其他网站的用途，除外，一些vps服务商也提到不得违反你居住的地方的法律。因此，不管怎么样，搭个vpn就基本必然是滥用，所以为什么还要纠结套个cdn是不是滥用呢？

**Comment by ArcCal** [comment]
还是别连累CDN服务商了吧

**Comment by murez** [comment]
你的流量对于 CF 来说算不上多少
